name: Simple Test

on:
  push:
    branches: [ main ]

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo test
        run: |
          echo "Hello from GitHub Actions!"
          echo "Current time: $(date)"
          echo "✅ Simple test completed"
