name: Update Cue Data

on:
  repository_dispatch:
    types: [cue-data-update]

jobs:
  update-cue-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update cue data
        run: |
          # Create cuetocue directory if it doesn't exist
          mkdir -p cuetocue
          
          # Write the real cue data from the macOS app
          echo '${{ toJson(github.event.client_payload.cueData) }}' > cuetocue/cuetocue-data.json
          
          # Write the real metadata from the macOS app
          echo '${{ toJson(github.event.client_payload.metadata) }}' > cuetocue/metadata.json
          
          # Debug: Show what we're writing
          echo "Cue data content:"
          cat cuetocue/cuetocue-data.json
          echo "Metadata content:"
          cat cuetocue/metadata.json
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cuetocue/cuetocue-data.json cuetocue/metadata.json
          git commit -m "Update cue data from macOS app: ${{ github.event.client_payload.metadata.filename }}" || exit 0
          git push